// AUDIO CAPTURE CONSTANTS
pub const AUDIO_CAPTURE_PIPELINE_NAME: &str = "AUDIO CAPTURE";
pub const CAPS_CHANNELS_AMOUNT: u8 = 2;

//AUDIO PLAYBACK CONSTANTS
pub const AUDIO_PLAYER_PIPELINE_NAME: &str = "AUDIO PLAYER";
pub const CAPS_AUDIO_PAYLOAD: u8 = 96;
pub const CAPS_AUDIO_CLOCKRATE: u64 = 48000;
pub const CAPS_AUDIO_ENCODING_NAME: &str = "OPUS";
