//VIDEO CAPTURE CONSTS
pub const VIDEO_CAPTURE_PIPELINE_NAME: &str = "VIDEO CAPTURE";
pub const GSTREAMER_FRAMES: i32 = 60;
pub const ENCODER_BITRATE: u32 = 10000;

//VIDEO PLAYER CONSTS
pub const VIDEO_PLAYER_PIPELINE_NAME: &str = "VIDEO PLAYER";
